<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"> 
<title>Notepad Application</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="css/style.css" rel="stylesheet">
</head>
    <body>
  <div class="container_l">
	<section id="content">
		<?php echo $this->form ?>
		<div class="button" style="height:42px">
			
		</div><!-- button -->
	</section><!-- content -->
</div><!-- container -->