<!DOCTYPE html>
<?php 
    
    $link_css = "css/style.css";
    $link_bootstrap = "css/bootstrap.css";
    $link_fontello = "css/fontello.css";
    $font_roboslab = "http://fonts.googleapis.com/css?family=Roboto+Slab";
    $jquery = "js/jquery-2.1.1.min.js";
    $angularjs = "js/angular.js";
    $skrypt = "js/script.js";

?>

<html ng-app>
<head>
<meta charset="utf-8"> 
<title>Notepad Application</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $this->baseUrl($link_css); ?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl($link_bootstrap); ?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl($link_fontello); ?>" rel="stylesheet">
<link href="<?php echo $font_roboslab ?>" rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="<?php echo $this->baseUrl("$jquery"); ?>">
    </script>
    <script type="text/javascript">var baseUrl = "<?php echo $this->baseUrl("");?>";
    </script>
</head>
    <body ng-controller="commentsController">
        <section class="navbar navbar-inverse navbar-static-top"\>
            <section class="user">
                <i class="icon-user sf-icon sf-icon-small"></i>
                <p>{{wynik[0].username}}</p>
                <a href="<?php echo $this->baseUrl ?>login/logout">Wyloguj</a>
            </section>
        </section>
        <h1 class="title text-center">Notepad Application</h1>
        <section class="Notepad container jumbotron box-shadow" id="notepad" >
            <ul ng-repeat="post in wynik"> 
                <li class="posty" ng-class="$no_high">
                    <h4  ng-click="showPost($index,$n)">{{post.title}}</h4>
                    <section class='time'>
                        <p>Autor: {{post.author}} </p>
                        <p>Data dodania: {{post.time}}</p>
                    </section>
                    <p>{{post.description}}</p>

                </li>
                 <button type="submit" ng-click="removePost($index)" class="usun btn btn-danger">Usuń</button>
            </ul>
            <ul ng-show="show()">
                <li class="posty">
                    <h4>{{name}}</h4>
                    <section class='time'>
                        <p>Autor: {{wynik[0].username}}</p>
                    </section>
                    <p>{{notka}}</p>
                </li>  
            </ul>
        </section>
        
        <section class="note container">
            <form class="form-horizontal" role="form" name="saveTemplateData"   ng-submit="submitForm()">
                <section class="form-group">
                    <label for="inputTitle" class="col-sm-1 control-label" >Tytuł</label>
                    <section class="col-sm-10">
                        <input type="Title" class="form-control" id="inputtitle" placeholder="Tytuł  Notatki"  ng-model="form.title">
                        <textarea class="form-control" rows="3" placeholder="Treść Notatki" ng-model="form.content"></textarea>
                        <button type="submit" ngClick="Submit" class="dodaj btn btn-success">Dodaj</button>
                    </section>
                </section>
            </form>
        </section>
    
<div>
  
  <table>
    <tr>
      <td>Directive</td>
      <td>How</td>
      <td>Source</td>
      <td>Rendered</td>
    </tr>
 
    <tr id="bind-html-with-trust">
      <td>ng-bind-html</td>
      <td>Bypass $sanitize by explicitly trusting the dangerous value</td>
      <td>
      <pre>&lt;div ng-bind-html="deliberatelyTrustDangerousSnippet()"&gt;
&lt;/div&gt;</pre>
      </td>
      <td><div ng-bind-html="deliberatelyTrustDangerousSnippet()"></div></td>
   
  </table>
  </div>

<script type="text/javascript" src="<?php echo $this->baseUrl("$angularjs"); ?>"></script>

<script src="<?php echo $this->baseUrl('js/bootstrap.js'); ?>" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl("$skrypt"); ?>"></script>
    </body>
</html>