<!DOCTYPE html>
<html ng-app>
<head>
<meta charset="utf-8"> 
<title>Notepad Application</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $this->baseUrl('css/style.css'); ?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('css/bootstrap.css'); ?>" rel="stylesheet">
<link href="<?php echo $this->baseUrl('css/fontello.css'); ?>" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery-2.1.1.min.js'); ?>">
    </script>
</head>
    <body ng-controller="commentsController">
        <section class="navbar navbar-inverse navbar-static-top"\>
            <section class="user">
                <i class="icon-user sf-icon sf-icon-small"></i>
                <p>{{wynik[0].username}}</p>
                <a href="http://projekt1.com/login/logout">Wyloguj</a>
            </section>
        </section>
        <h1 class="title text-center">Notepad Application</h1>
        <section class="Notepad container jumbotron box-shadow" id="notepad" >
            <ul ng-repeat="post in wynik"> 
                <li class="posty" ng-class="$no_high">
                    <h4  ng-click="showPost($index,$n)">{{post.title}}</h4>
                    <section class='time'>
                        <p>Autor: {{post.author}} </p>
                        <p>Data dodania: {{post.time}}</p>
                    </section>
                    <p>{{post.description}}</p>

                </li>
                 <button type="submit" ng-click="removePost($index)" class="usun btn btn-danger">Usuń</button>
            </ul>
            <ul ng-show="show()">
                <li class="posty">
                    <h4>{{name}}</h4>
                    <section class='time'>
                        <p>Autor: {{wynik[0].username}}</p>
                    </section>
                    <p>{{notka}}</p>
                </li>  
            </ul>
        </section>
        
        <section class="note container">
            <form class="form-horizontal" role="form" name="saveTemplateData"   ng-submit="submitForm()">
                <section class="form-group">
                    <label for="inputTitle" class="col-sm-1 control-label" >Tytuł</label>
                    <section class="col-sm-10">
                        <input type="Title" class="form-control" id="inputtitle" placeholder="Tytuł  Notatki"  ng-model="form.title">
                        <textarea class="form-control" rows="3" placeholder="Treść Notatki" ng-model="form.content"></textarea>
                        <button type="submit" ngClick="Submit" class="dodaj btn btn-success">Dodaj</button>
                    </section>
                </section>
            </form>
        </section>

<script type="text/javascript" src="<?php echo $this->baseUrl('js/angular.js'); ?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap.js'); ?>" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/script.js'); ?>"></script>
    </body>
</html>